spring:
  profiles:
    active: dev
server:
  port: 8081

############日志##############
logging:
  level: debug
#指定目录,与logging.file冲突
#当前磁盘的根路径下创建spring文件夹和里面的log文件夹,使用日志spring.log默认文件
  path: /spring/log
#不指定路径,就在当前项目下生产springboot.log日志
#可以指定完整的路径:
  file: springboot.log
# 在控制台输出的日志的格式
  pattern:
    console: